[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulator = { path = "../emulator" }
assembler = { path = "../assembler" }
eframe = "0.22.0"
chrono = "0.4.28"
tinyfiledialogs = "3.9.1"
